#ifndef GUI_ID_H_INCLUDED
#define GUI_ID_H_INCLUDED

enum GuiID
{
	GUI_ID_RECT_MENU = 1,
	GUI_ID_RECT_OPTION,
	GUI_ID_BUTTON_NEW_GAME,
	GUI_ID_BUTTON_CONTINUE,
	GUI_ID_BUTTON_OPTIONS,
	GUI_ID_BUTTON_QUIT,
	GUI_ID_BUTTON_MOVE_FORWARD_TEXT,
	GUI_ID_BUTTON_MOVE_FORWARD_KEY,
};

#endif // GUI_ID_H_INCLUDED

