#ifndef GUI_ID_H_INCLUDED
#define GUI_ID_H_INCLUDED

enum GuiID
{
	GUI_ID_RECT_MENU_TITLE = 1,
	GUI_ID_RECT_MENU_SETTINGS,

	GUI_ID_BUTTON_NEW_GAME,
	GUI_ID_BUTTON_LOAD,
	GUI_ID_BUTTON_SETTINGS,
	GUI_ID_BUTTON_QUIT,
	GUI_ID_BUTTON_FORWARD,
	GUI_ID_BUTTON_BACKWARD,
	GUI_ID_BUTTON_TURN_RIGHT,
	GUI_ID_BUTTON_TURN_LEFT,
	GUI_ID_BUTTON_STRAFE_RIGHT,
	GUI_ID_BUTTON_STRAFE_LEFT,
	GUI_ID_BUTTON_RUN,
	GUI_ID_BUTTON_JUMP,
	GUI_ID_BUTTON_SHOOT,
	GUI_ID_BUTTON_PAUSE,

	GUI_ID_TEXT_FORWARD,
	GUI_ID_TEXT_BACKWARD,
	GUI_ID_TEXT_TURN_RIGHT,
	GUI_ID_TEXT_TURN_LEFT,
	GUI_ID_TEXT_STRAFE_RIGHT,
	GUI_ID_TEXT_STRAFE_LEFT,
	GUI_ID_TEXT_RUN,
	GUI_ID_TEXT_JUMP,
	GUI_ID_TEXT_SHOOT,
	GUI_ID_TEXT_PAUSE,
};

#endif // GUI_ID_H_INCLUDED

